  services:
    frontend:
      build:
        context: Frontend
        target: development
      ports:
        - 3020:3000 
      stdin_open: true
      volumes:
        - ./Frontend:/usr/src/app
        - /usr/src/app/node_modules
      restart: always
      environment:
        - BACKEND_URI=http://backend:3000
      env_file:
        - ./Frontend/.env
      networks:
        - pharmacy-front-network
      depends_on:
        - backend

    backend:
      build:
        context: Backend
        target: development
      volumes:
        - ./Backend:/usr/src/app
        - /usr/src/app/node_modules
      restart: always
      environment:
        - MONGODB_URI=mongodb://database:27017/pharmacy?directConnection=true
        - CHOKIDAR_USEPOLLING=true
      networks:
        - pharmacy-front-network
        - pharmacy-back-network
      env_file:
        - ./Backend/.env
      depends_on:
        database:
          condition: service_healthy
      expose: 
        - 3000
      ports:
        - 3021:3000   # for test

    database:

      image: mongo:4.2.0
      healthcheck:
        test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
        interval: 3s
        retries: 5
        start_period: 30s
      volumes:
        - db_volume:/data/db
      restart: always
      environment:
        ALLOW_EMPTY_PASSWORD: 'yes'
      command : mongod --logpath /var/log/mongodb/mongod.log --logappend
      networks:
        - pharmacy-back-network
      expose:
        - 27017
      ports:
        - 3022:27017    # for test
        


  networks:
    pharmacy-front-network:
    pharmacy-back-network:

  volumes:
    db_volume:
